language: java
jdk:
- oraclejdk8

before_install:
- openssl aes-256-cbc -K $encrypted_498771521deb_key -iv $encrypted_498771521deb_iv
  -in oss_secring.gpg.enc -out oss_secring.gpg -d

install:
- ./gradlew clean test assemble uploadArchives
